[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_bike_sharing"
author = "Nikita Matta"
author-email = "nikita.matta@student.edu"

